### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MikolajBalcerek** [crouchred/speaker-recognition-py3#4]
Hey,
I'd be interested in using your project as a dependency in my Speaker Recognition project as one of the methods used in a comparison of various methods available. 
Would you mind to specify the license that your modifications are under? 
I see that the original project used an Apache License, but I am unsure whether you intended your changes to be under that license as well. 

Thanks,
Mikołaj

**Comment by crouchred** [comment]
Sure, Apache License added

**Comment by MikolajBalcerek** [comment]
Thanks!
