### ISSUE TITLE
"/tmp/person* ./mary" are this directories of wav files?

### ISSUE THREAD

**Issue by mehadi-trackrep** [crouchred/speaker-recognition-py3#5]
Please tell me that is these directories stores the wav file of the person related in person folder and
mary's speech in mary folder?

**Comment by crouchred** [comment]
'/tmp/person*' stores the folder and './mary' stores the wav files.
When using wildcard like '/tmp/person*', it will use every folder detected as label.
When using specific folder like ' ./mary',  it will use folder name 'mary' as label.

**Comment by mehadi-trackrep** [comment]
Ok, Thanks!
