### ISSUE TITLE
model.out

### ISSUE THREAD

**Issue by abdvlz** [crouchred/speaker-recognition-py3#7]
i didnt understand how would multiple wav files of different speakers are compared with only one model.

it always outputs score of 1.0 and arbitrary result.

could you please explain ??

thanks lots

**Comment by crouchred** [comment]
It does generate multiple models.
Maybe you put all wav files in the same folder and then they are identified as one label?
Please try put each file in a folder if you want to use a single file as a label.
[using wildcard like '/tmp/person*', it will use every folder detected as label.
W](https://github.com/crouchred/speaker-recognition-py3/issues/5)

**Comment by alonyomtov123** [comment]
the output for me is also always 1.0. can someone help?
